version: '3.8'

services:
  server:
    container_name: server_pr2
    build: server/
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
  db:
    build: db/
    ports:
      - "3308:3308"
    container_name: db_pr2
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
